apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-knative-git
spec:
  type: git
  params:
    - name: revision
      value: b1.0
    - name: url
      value: https://github.com/knative-sample/tekton-knative
